### ISSUE TITLE
运行build.sh脚本报错

### ISSUE THREAD

**Issue by cui3093** [arkdb/arkproxy#1]
-- Configuring done
CMake Error at cmake/libutils.cmake:108 (ADD_LIBRARY):
  Cannot find source file:

    debug_sync_service.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  libservices/CMakeLists.txt:36 (ADD_CONVENIENCE_LIBRARY)

CMake Error at sql/CMakeLists.txt:173 (ADD_LIBRARY):
  Cannot find source file:

    debug_sync.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at cmake/libutils.cmake:108 (ADD_LIBRARY):
  No SOURCES given to target: mysqlservices
Call Stack (most recent call first):
  libservices/CMakeLists.txt:36 (ADD_CONVENIENCE_LIBRARY)

CMake Error at sql/CMakeLists.txt:173 (ADD_LIBRARY):
  No SOURCES given to target: sql

CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by jesset** [comment]
什么环境下构建的？操作系统、gcc版本？
另外 build.sh 加参数了吗？

**Comment by jesset** [comment]
已经补齐了缺失的源文件，请 pull 更新后再试。造成您的不便还请谅解。

**Comment by cui3093** [comment]
@jesset 请问你能按照这个教程成功的编译出来吗？

**Comment by cui3093** [comment]
以下是我的安装环境
`[root@localhost arkproxy]# uname -a
Linux localhost.localdomain 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost arkproxy]# gcc --version
gcc (GCC) 8.0.1 20180324 (Red Hat 8.0.1-0.20)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@localhost arkproxy]# g++ --version
g++ (GCC) 8.0.1 20180324 (Red Hat 8.0.1-0.20)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@localhost arkproxy]# cmake --version
cmake3 version 3.17.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
`

**Comment by cui3093** [comment]
[ 11%] Built target vio
Scanning dependencies of target feedback
[ 11%] Building CXX object plugin/feedback/CMakeFiles/feedback.dir/feedback.cc.o
In file included from /root/arkdb/arkproxy/include/my_global.h:332,
                 from /root/arkdb/arkproxy/sql/sql_class.h:23,
                 from /root/arkdb/arkproxy/plugin/feedback/feedback.h:17,
                 from /root/arkdb/arkproxy/plugin/feedback/feedback.cc:16:
/usr/include/c++/8/math.h:65:12: error: ‘constexpr bool std::isinf(double)’ conflicts with a previous declaration
 using std::isinf;
            ^~~~~
In file included from /usr/include/features.h:365,
                 from /usr/include/pthread.h:21,
                 from /root/arkdb/arkproxy/include/my_global.h:278,
                 from /root/arkdb/arkproxy/sql/sql_class.h:23,
                 from /root/arkdb/arkproxy/plugin/feedback/feedback.h:17,
                 from /root/arkdb/arkproxy/plugin/feedback/feedback.cc:16:
/usr/include/bits/mathcalls.h:201:1: note: previous declaration ‘int isinf(double)’
 __MATHDECL_1 (int,isinf,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^~~~~~~~~~~~
In file included from /root/arkdb/arkproxy/include/my_global.h:332,
                 from /root/arkdb/arkproxy/sql/sql_class.h:23,
                 from /root/arkdb/arkproxy/plugin/feedback/feedback.h:17,
                 from /root/arkdb/arkproxy/plugin/feedback/feedback.cc:16:
/usr/include/c++/8/math.h:66:12: error: ‘constexpr bool std::isnan(double)’ conflicts with a previous declaration
 using std::isnan;
            ^~~~~
In file included from /usr/include/features.h:365,
                 from /usr/include/pthread.h:21,
                 from /root/arkdb/arkproxy/include/my_global.h:278,
                 from /root/arkdb/arkproxy/sql/sql_class.h:23,
                 from /root/arkdb/arkproxy/plugin/feedback/feedback.h:17,
                 from /root/arkdb/arkproxy/plugin/feedback/feedback.cc:16:
/usr/include/bits/mathcalls.h:234:1: note: previous declaration ‘int isnan(double)’
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^~~~~~~~~~~~
[ 11%] Building C object strings/CMakeFiles/strings.dir/ctype-utf8.c.o
make[2]: *** [plugin/feedback/CMakeFiles/feedback.dir/feedback.cc.o] Error 1
make[1]: *** [plugin/feedback/CMakeFiles/feedback.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 12%] Building C object strings/CMakeFiles/strings.dir/ctype-win1250ch.c.o
[ 12%] Building C object strings/CMakeFiles/strings.dir/ctype.c.o
[ 12%] Building C object strings/CMakeFiles/strings.dir/decimal.c.o
[ 12%] Building C object strings/CMakeFiles/strings.dir/dtoa.c.o
[ 12%] Building C object strings/CMakeFiles/strings.dir/int2str.c.o
[ 12%] Building C object strings/CMakeFiles/strings.dir/is_prefix.c.o
[ 12%] Building C object strings/CMakeFiles/strings.dir/llstr.c.o
[ 12%] Building C object strings/CMakeFiles/strings.dir/longlong2str.c.o
[ 12%] Building C object strings/CMakeFiles/strings.dir/my_strtoll10.c.o
[ 13%] Building C object strings/CMakeFiles/strings.dir/my_vsnprintf.c.o
[ 13%] Building C object strings/CMakeFiles/strings.dir/str2int.c.o
[ 13%] Building C object strings/CMakeFiles/strings.dir/str_alloc.c.o
[ 13%] Building C object strings/CMakeFiles/strings.dir/strcend.c.o
[ 13%] Building C object strings/CMakeFiles/strings.dir/strend.c.o
[ 13%] Building C object strings/CMakeFiles/strings.dir/strfill.c.o
[ 13%] Building C object strings/CMakeFiles/strings.dir/strmake.c.o
[ 13%] Building C object strings/CMakeFiles/strings.dir/strmov.c.o
[ 13%] Building C object strings/CMakeFiles/strings.dir/strnmov.c.o
[ 14%] Building C object strings/CMakeFiles/strings.dir/strxmov.c.o
[ 14%] Building C object strings/CMakeFiles/strings.dir/strxnmov.c.o
[ 14%] Building C object strings/CMakeFiles/strings.dir/xml.c.o
[ 14%] Building C object strings/CMakeFiles/strings.dir/strmov_overlapp.c.o
[ 14%] Building C object strings/CMakeFiles/strings.dir/my_strchr.c.o
[ 14%] Building C object strings/CMakeFiles/strings.dir/strcont.c.o
[ 14%] Building C object strings/CMakeFiles/strings.dir/strappend.c.o
[ 14%] Building C object strings/CMakeFiles/strings.dir/json_lib.c.o
[ 14%] Linking C static library libstrings.a
[ 14%] Built target strings
make: *** [all] Error 2

**Comment by jesset** [comment]
应该是编译器版本的原因，这是我昨天的环境，gcc4.8 ：

```
[root@ ~]# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@ ~]# g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by cui3093** [comment]
@jesset ，多谢指正，确实是编译器的问题.
